spring:
  datasource:
    url:
      jdbc:mysql://localhost:3306/chat
    username: woong
    password: Jhan00254!
    driver-class-name: com.mysql.cj.jdbc.Driver
  #  datasource:
  #    url: jdbc:mysql://ebh2y8tqym512wqs.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/dtp125vfu1wqqxc3
  #    username: g2bd5ln75c8aavzp
  #    password: wwj12mfctwj7r1ua
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    hikari:
  #      maximum-pool-size: 9
  jpa:
    hibernate:
      ddl-auto: update # TODO: 배포 시 ddl-auto 삭제
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 459226304104-0q3j7ese22f3fj7s1kq81te98djfqsc9.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - profile
              - email
          naver:
            client-id: W9UmyrWcgG50ZcXMQfG0
            client-secret: FgPRGI7mZC
            client-authentication-method: post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - nickname
              - email
            client-name: Naver
          kakao:
            client-id: 5c5d2397c3cbf72f8b6111fb80efca0b
            client-secret: 2PFjvHkZGxSeJAUUp6yPIJXVf8w4pZAV
            client-authentication-method: post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - account_email
            client-name: Kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id

logging:
  level:
    com.example.potatowoong: debug

jwt:
  secret: 9338f60fb540cc5f56629a3f378bd3548d10b57f4b47698274a7308f4da25c83cabc8ca13fa03ebb90b940f20d6ef20940168a6c91ee17d985663b653a75ffcc
server:
  port: 8080

app:
  oauth2:
    authorizedRedirectUri: "http://localhost:3000/oauth2/redirect"